# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17.20
# Mod Properties
mod_version=1.0
maven_group=org.mcsebi
archives_base_name=whereismyshulker
# Dependencies
fabric_api_version=0.160.0+26.2
